### ISSUE TITLE
Can pipeline use date math?

### ISSUE THREAD

**Issue by genadyk** [raffis/mongodb-query-exporter#12] opened 2020-10-08 11:19 UTC
Hi,
In my case I would like to export some aggregation pipeline result as gauge metric.
In my particular case I want to limit the aggregation to last hour.

Is that supported and if so can you post an example please?

MongoDB shell pipeline is:
```           
[
                { 
                    $match: {
                        $and: [
                            {startTime: {$gte: new Date(ISODate().getTime() - 1000 * 60 * 60)}},
                            {taskName: "CREATE_PO_FILE"},
                            {success: true}
                        ]
                    }
                }, 
                {$count: 'poGeneratedCount'}
]
```

**Comment by raffis** [comment] 2020-10-08 19:51
@genadyk This is  not possible, at least not now. MongoDB does not support to parse something like $currentDate for match operation. Your example works in the Mongo console where Date/ISODate is evaluated before sending the query but this would not work stored as json since there is nothing to interpret this. The only way to represent the date is an exact date like `{"startTime": {"$date": "xxxx-xx-xx....."}} which obviously is nothing you need. And there is no way to include js in an aggregation pipeline (unlike a query where this is possible with $where).

So the only way this would be possible is to somewhat prerender the pipeline in the query-exporter which is not yet supported.

**Comment by xuanyuanaosheng** [comment] 2020-10-10 10:30
@raffis  I had the same problem, I think this is a universal requirement.

**Comment by genadyk** [comment] 2020-10-11 19:01
I've ended up with the following workaround:
```
            [ { "$sort": { "startTime": -1 }}, 
              {"$limit": 100000}, 
              { "$facet": {
                "result": [{
                  "$match":{
                    "$and": [
                    {
                      "taskName": "CREATE_PO_FILE"
                    },
                    {
                      "success": true
                    },
                    {
                      "$expr": {
                        "$gt": [
                          "$startTime",
                          {
                            "$subtract": [
                              "$$NOW",
                              3600000
                            ]
                          }
                        ]
                      }
                    }
                  ]}}, 
                  {"$count": "poGeneratedCount"} ]
              }}, 
              {"$project": {
                  "count": { "$ifNull": [{ "$arrayElemAt": ["$result.poGeneratedCount", 0] }, 0]}
              }}
            ]
```
Ugly but does the work for my use-case.

**Comment by xuanyuanaosheng** [comment] 2020-10-13 01:31
@genadyk   Thanks,

**Comment by xuanyuanaosheng** [comment] 2020-10-20 01:31
@raffis   Any update?

**Comment by raffis** [comment] 2020-10-20 06:29
> @raffis Any update?

The problem is how such a thing would be implemented and if that even makes sense. We would need a some kind of a js interpreter to render that query and this sounds like out of scope of this project. Any suggestions welcome.

I like the workaround @genadyk posted, I wasn't aware that `$$NOW` works in a $match stage. If your use case is the same  (current date) I suggest you go with that solution.

**Comment by xuanyuanaosheng** [comment] 2020-10-21 01:49
@raffis This is a monitoring requirements, we want to get the query data in last X minutes.

**Comment by raffis** [comment] 2020-11-11 23:34
> This is a monitoring requirements, we want to get the query data in last X minutes.
> 
> @raffis Any update?

Well with MongoDB >= 4.2 you actually should use $$NOW as proposed here, also see examples: https://github.com/raffis/mongodb-query-exporter/blob/master/example/configv2.yaml#L80-L87

Support for javascript in the form of `new Date(ISODate().getTime() - 1000 * 60 * 60)` is not supported yet and probably not anytime soon since it would add too much complexity to a simple problem.

**Comment by xuanyuanaosheng** [comment] 2020-11-19 04:20
@raffis   Thanks.

**Closed** 2021-01-18 21:48 UTC
Labels: enhancement

**Comment by xuanyuanaosheng** [comment] 2021-04-28 11:01
@raffis  

I think use the Mongo console function like Date/ISODate is very useful, because we can put it in the config file directly.

Could your please help with this?

db.ContractStatusChange.aggregate([
{$match:{'cDate':{$gt:**ISODate**("2021-04-22T05:00:00Z"),$lt:ISODate("2021-04-23T05:00:00Z")},
'data.contractStatus':{$in:['SIGNED','ACTIVE','CANCELLED','REJECTED']}}},
{$project:{"data.contractNumber":true,"data.productChannel":true}},
{$group:{_id:{'no':'$data.contractNumber','channel':'$data.productChannel'}}},
{$group:{_id:'$_id.channel',count:{$sum:1}}}
]);
