### ISSUE TITLE
How to return a count of 0 from the pipeline

### ISSUE THREAD

**Issue by davesykeselateral** [raffis/mongodb-query-exporter#22] opened 2021-03-01 16:21 UTC
#### Is your feature request related to a problem? Please describe
I am attempting to produce a metric that is the number of items, and that count can be 0. In this case I am trying to get the count of stuck orders in the system.

Pipeline:
```
[
  {"$match": {"status": "STUCK"}},
  {"$count": {"total"}
]
```
This works great when there is at least 1 stuck order, however, if there are none, then there are no documents going through the pipeline, so the $count step does not do anything, and 0 records are returned, which means the mongodb-query-exporter does not see this as a valid metric and does not report it. From looking around, the recommended approach is to see if 0 records are returned from a $count step in a pipeline, interpret this as 0 records. I do not see a way of doing this in mongodb-query-exporter currently. 

So far I have managed to come up with adding an item into the pipeline just before the count, then subtracting 1 from it at the end, but not very nice!

#### Describe the solution you'd like
A way of returning a 0 count

**Comment by raffis** [comment] 2021-03-02 18:12
That's indeed the case, but works as intended. If there are no documents we can't create a metric. For instance you would also not have any fields to take in as labels (if you have labels configured).

How does your metric configuration look like? And whats the use case on the prometheus side, how do you want to query the metric?

**Comment by OleksandrGrabko** [comment] 2021-04-07 17:16
In general we query MongoDB and query return some integer > 0 or Null. We can wrap query on MongoDB level:

{ $ifNull: [ 
db.getCollection("service-item").aggregate([
      {  
          "$match": {
....

In this case we'll get integer or 0 instead of Null.
But we can't put $ifNull in exporter as it is level up for collection parameter.

**Comment by Ferparishuertas** [comment] 2021-10-30 09:36
Same happens on our case. We cannot generate 0 gauge, if no document o aggregation, with mongo query yes

**Comment by guillaumelecerf** [comment] 2021-11-03 15:53
I added an option to handle empty result set as zero, see https://github.com/raffis/mongodb-query-exporter/pull/32/files
Feel free to tell me whether it could be merged.

**Comment by guillaumelecerf** [comment] 2021-11-04 16:14
You can now add this to your metric definition:
```
  overrideEmpty: true
  emptyValue: 0
```

**Closed** 2021-12-22 11:13 UTC
Labels: question
